#!/usr/bin/env python3
import sys, os
pfx = None
args = sys.argv[1:]
i = 0
while i < len(args):
    if args[i] == "-of" and i + 1 < len(args):
        pfx = args[i + 1]; i += 2; continue
    i += 1
if pfx:
    with open(pfx + ".txt", "w") as out:
        out.write("[0:0:0.0 --> 0:0:2.500] open a new tab\n"
                  "[0:0:02.500 --> 0:0:04.000] click 【tok】\n")
